path_planning_and_following:
  strict_path_follower:
    motion_states:
      stair_climbing:
        max_vel_theta: 0.1
        max_vel_x: 0.3
        max_vel_x_backwards: 0.3
        max_vel_y: 0.1
        min_vel_theta: 0.0
        min_vel_x: 0.3
        min_vel_y: 0.0
        weight_shortest_path: 40.0
stack_launcher:
  stacks:
    navigation:
      nodes:
        near_field_mapping_preset_selector:
          enabled: true
trekker:
  modes:
    stair_climbing:
      policy: 'stair_climbing_2022_05_05_09_35_48_1500.pt'
      elevation_map_nan_behavior: 'plane_approximation'