motion_control_manager:
  available_controllers:
    controllers:
      test_model:
        emergency_controller: emergency_freeze
        name: test_model
        parameter_package: ''
        parameter_path: ''
        plugin_name: anymal_ctrl_test_model_ros::TestModelRos
      test_whole_body_control:
        emergency_controller: emergency_freeze
        name: test_whole_body_control
        parameter_package: anymal_d
        parameter_path: config/non_ros/motion_control/anymal_ctrl_test
        plugin_name: anymal_ctrl_test_whole_body_control_ros::TestWholeBodyControllerRos
  motion_transitioner:
    motion_states:
      scan_environment:
        direct_transit_state: square_up
    transitions:
      scan_environment:
        connections:
          square_up: 10.0
        motion:
          motion_controller: free_gait
          operation_mode: scan_environment
          reference_type: action
        preempt_state: _preempted
        target_state: scan_environment
free_gait_action_loader:
  free_gait_action_packages:
    priority_95: anymal_calibration_actions
gui:
  navigation:
    diagnostic_mode: true
interaction_marker:
  plugin_setup:
    plugins:
      30_publish_locomotion_walk_to_pose_goal:
        parameters:
          auto_control_required: true
          entry_text: Walk To Pose Without Navigation
          pose_frame_id: odom
          server_name: /locomotion_actions/goal_pose_action_server
        type: interaction_marker_plugin_locomotion::InteractionMarkerPluginLocomotion
      40_navigation_manager:
        parameters:
          actions:
            navigate_to_goal:
              topic: /path_planning_and_following/navigate_to_goal
              use_spin_thread: true
            plan_path:
              topic: /path_planning_and_following/plan_path
              use_spin_thread: true
          auto_control_required: true
          entry_texts:
            navigation_goal: Navigate to Goal
            plan_path: Plan from start to goal
            plan_path_menu: Plan path
            plan_path_set_goal: Set goal pose
            plan_path_set_start: Set start pose
          navigation_goal:
            tolerance:
              rotation: 0.16
              translation: 0.1
          pose_frame_id: map
        type: interaction_marker_plugin_navigation_manager::InteractionMarkerPluginNavigationManager
joy_motion_control:
  motion_mapping:
    scan_environment: scan_environment
