behavior_engine_execute_mission_api: # Absolute names, as these parameters are read by different nodes.
  monitor: &behavior_engine_execute_mission_monitor
    subscribers:
      state_execution_events:
        queue_size: 10
        topic: /behavior_engine/execute_mission/mission_execution_events
      state_progressed_events:
        queue_size: 10
        topic: /behavior_engine/execute_mission/mission_progressed_events
inspection_presenter:
  assets_fetching:
    parameter_key: "/environment/objects"
  event_interpreters:
    auditive_inspection_frequency:
      queue_size: 1
      topic: "/inspection_manager_ros/inspect_auditive_item/frequency/result"
    auditive_inspection_simple:
      queue_size: 1
      topic: "/inspection_manager_ros/inspect_auditive_item/simple/result"
    inspection_intelligence:
      queue_size: 1
      topic: "/inspection_manager_ros/inspect_inspection_intelligence_object/result"
    visual_inspection_dial:
      queue_size: 1
      topic: "/inspection_manager_ros/inspect_visual_item/dial/result"
    visual_inspection_simple:
      queue_size: 1
      topic: "/inspection_manager_ros/inspect_visual_item/simple/result"
    visual_inspection_thermal:
      queue_size: 1
      topic: "/inspection_manager_ros/inspect_visual_item/thermal/result"
  metadata_retrieval:
    monitor_mission:
      <<: *behavior_engine_execute_mission_monitor
  number_threads_ros_spinner: 2
  transform_retrieval:
    coordinate_frames:
      mission_frame: "map"
      robot_frame: "base"
    transform_wait_timeout: 0.1
gui:
  toolbar_menu:
    plugins:
      rqt_anymal_data_sync:
        icon_path: :/images/data_sync.svg
        label: Data Sync
        location: toolbar
        name: rqt_anymal_data_sync/AnymalDataSyncPlugin
        object_name: AnymalDataSyncWidget
        order: 2
stack_launcher:
  nodes:
    ads_agent_lpc:
      roslaunch:
        args: ads.local:58050
        name: ads_agent_lpc
        node_type: ads_agentd
        output: screen
        package: anymal_data_sync_agent
        respawn: true
    ads_agent_npc:
      roslaunch:
        args: ads.local:58050
        name: ads_agent_npc
        node_type: ads_agentd
        output: screen
        package: anymal_data_sync_agent
        respawn: true
    inspection_presenter:
      roslaunch:
        name: inspection_presenter
        node_type: inspection_presentation_node
        output: screen
        package: inspection_presentation
  stacks:
    lpc_background:
      nodes:
        ads_agent:
          enabled: true
          name: ads_agent_lpc
    npc_background:
      nodes:
        ads_agent:
          enabled: true
          name: ads_agent_npc
    inspection:
      nodes:
        inspection_presenter:
          enabled: true
          name: inspection_presenter


