# The following config is necessary, because parameters (e.g. perceptive_walk motion state) cannot be removed via YAML if toggle is on.
motion_control_manager:
  motion_transitioner:
    motion_states:
      perceptive_walk: # Allows to use perceptive Trekker in parallel to blind Trekker.
        direct_transit_state: ""
    transitions:
      perceptive_walk:
        connections:
          run: 1.0
          square_up: 2.5
          stair_climbing: 1.0
          stand: 2.0
          walk: 1.0
        motion:
          motion_controller: trekker
          operation_mode: perceptive_walk
          reference_type: twist
        preempt_state: _preempted
        target_state: perceptive_walk
      freeze:
        connections:
          perceptive_walk: 1.0
      walk:
        connections:
          perceptive_walk: 1.0
path_planning_and_following:
  strict_path_follower:
    motion_states:
      perceptive_walk:
        dt_ref: 0.4
        acc_lim_theta: 0.45
        max_vel_theta: 0.9
        max_vel_x: 0.6
        max_vel_x_backwards: 0.6
        max_vel_y: 0.45
        min_vel_theta: 0.01
        min_vel_x: 0.02
        min_vel_y: 0.02
        weight_shortest_path: 4.0
