robot_behavior_plugins:
  robot_behavior:
    enable_sensor_notifications: true
    enable_sensor_reactions: true
    enable_sensor_soft_reactions: true
sensor_notification_behavior_plugins:
  supervise_battery_combined_temperature:
    topic: /pdb/behavior/battery_combined_temperature
  supervise_battery_current:
    topic: /pdb/behavior/battery_current
  supervise_battery_humidity:
    topic: /pdb/behavior/battery_humidity
  supervise_battery_perm_fail:
    topic: /pdb/behavior/battery_permanent_fail
  supervise_battery_pressure:
    topic: /pdb/behavior/battery_pressure
  supervise_battery_temperature:
    topic: /pdb/behavior/battery_temperature
  supervise_body_temp:
    topic: /pdb/behavior/body_temperature
  supervise_customer_12v:
    topic: /pdb/behavior/customer_12v
  supervise_customer_48v:
    topic: /pdb/behavior/customer_48v
  supervise_fan_speed:
    topic: /pdb/behavior/fan_speed
  supervise_main_body_humidity:
    topic: /pdb/behavior/main_body_humidity
  supervise_main_body_pressure:
    topic: /pdb/behavior/main_body_pressure
  supervise_robot_sensors:
    topic: /pdb/behavior/robot_sensors
