operational_mode_manager:
  subscribers:
    user_interaction_mode:
      queue_size: 1
      topic: /behavior_engine/user_interaction_mode
environment_visualizer:
  control_lease:
    subscribers:
      user_interaction_mode: /behavior_engine/user_interaction_mode
interaction_marker:
  control_lease:
    subscribers:
      user_interaction_mode: /behavior_engine/user_interaction_mode
gui:
  control_lease:
    subscribers:
      user_interaction_mode: /behavior_engine/user_interaction_mode
    services:
      set_user_interaction_mode: /behavior_engine/set_user_interaction_mode
robot_behavior_plugins:
  monitor_behavior_mode:
    publishers:
      notify_user_interaction_mode:
        topic: /behavior_engine/user_interaction_mode
        queue_size: 1
        latch: true
    services:
      set_user_interaction_mode: /behavior_engine/set_user_interaction_mode
