launch:
  feature_toggles:
    state_estimation: simulated
    slam: simulated
    point_cloud_odometry: simulated
    environment_data_package: playground_data
    environment_config: default
    docking: disabled
    inspection_payload: disabled
    auditive_inspection_frequency: disabled
    visual_inspection_dial: disabled
    inspection_intelligence: disabled
    diagnostic_mode: disabled
    data_synchronization: disabled
gui:
  toolbar_menu:
    plugins:
      rqt_gazebo_interface:
        label: Simulation
        location: menu_advanced
        name: GazeboInterfacePlugin
        object_name: GazeboInterface
        order: 100
motion_control_manager:
  controller:
    simulation: true
load_anymal_description:
  custom_parameters:
    simulation: true
monitor_network_llpc:
  simulation: true
monitor_network_op:
  simulation: true
path_planning_and_following:
  simulation: true
rqt_motion_control:
  simulation: true
slam:
  simulated_localizer:
    localization_trigger_method: 0
stack_launcher:
  stacks:
    locomotion:
      nodes:
        depth_camera_front_lower_depth_image_to_point_cloud:
          enabled: false
        depth_camera_front_upper_depth_image_to_point_cloud:
          enabled: false
        depth_camera_rear_lower_depth_image_to_point_cloud:
          enabled: false
        depth_camera_rear_upper_depth_image_to_point_cloud:
          enabled: false
        depth_camera_front_lower_plane_detector:
          enabled: false
        depth_camera_front_upper_plane_detector:
          enabled: false
        depth_camera_rear_lower_plane_detector:
          enabled: false
        depth_camera_rear_upper_plane_detector:
          enabled: false
        depth_camera_front_lower_point_cloud_self_filter:
          enabled: false
        depth_camera_front_upper_point_cloud_self_filter:
          enabled: false
        depth_camera_rear_lower_point_cloud_self_filter:
          enabled: false
        depth_camera_rear_upper_point_cloud_self_filter:
          enabled: false
        elevation_mapping:
          enabled: false
    navigation:
      nodes:
        point_cloud_filter:
          enabled: false
    post_process_config:
      nodes:
        load_dodgeball_description:
          enabled: true
    simulation_environment:
      nodes:
        depth_camera_depth_aligned_to_infra1_topic_relay_sim_front_lower:
          enabled: false
        depth_camera_infra1_info_topic_relay_sim_front_lower:
          enabled: false
        depth_camera_infra1_topic_relay_sim_front_lower:
          enabled: false
        depth_camera_depth_aligned_to_infra1_topic_relay_sim_front_upper:
          enabled: false
        depth_camera_infra1_info_topic_relay_sim_front_upper:
          enabled: false
        depth_camera_infra1_topic_relay_sim_front_upper:
          enabled: false
        depth_camera_depth_aligned_to_infra1_topic_relay_sim_left:
          enabled: false
        depth_camera_infra1_info_topic_relay_sim_left:
          enabled: false
        depth_camera_infra1_topic_relay_sim_left:
          enabled: false
        depth_camera_depth_aligned_to_infra1_topic_relay_sim_rear_lower:
          enabled: false
        depth_camera_infra1_info_topic_relay_sim_rear_lower:
          enabled: false
        depth_camera_infra1_topic_relay_sim_rear_lower:
          enabled: false
        depth_camera_depth_aligned_to_infra1_topic_relay_sim_rear_upper:
          enabled: false
        depth_camera_infra1_info_topic_relay_sim_rear_upper:
          enabled: false
        depth_camera_infra1_topic_relay_sim_rear_upper:
          enabled: false
        depth_camera_depth_aligned_to_infra1_topic_relay_sim_right:
          enabled: false
        depth_camera_infra1_info_topic_relay_sim_right:
          enabled: false
        depth_camera_infra1_topic_relay_sim_right:
          enabled: false
state_estimator:
  simulation: true
  tsif:
    angular_variance_threshold: 0.00015
system_behavior_plugins:
  start_up:
    simulation: true
use_sim_time: true
process_info_logger:
  enabled: False
param_logger:
  enabled: False
user_interaction_mode_manager:
  communication_relay_profiles:
    direct_control:
      services:
        go_to_low_level_controller_life_cycle_state:
          enabled: false
        set_fan_speed:
          enabled: false
        switch_low_level_controller_state:
          enabled: false
    direct_control_rcu:
      services:
        switch_low_level_controller_state:
          enabled: false
